# Generated by Django 4.1.2 on 2022-10-19 15:16

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0003_remove_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FIO',
            field=models.CharField(default='ФИО', max_length=300, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='Логин', error_messages={'unique': 'Логин должен быть уникальным'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
