# Generated by Django 4.1.2 on 2022-10-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0004_user_fio_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
